---
- hosts: all
  connection: local
  vars: 
    - nextcloud_version: "17.0.1"
  vars_prompt:
    - name: mysql_root_password
      prompt: "MariaDB root password"
      private: yes
    - name: nextcloud_mariadb_password
      prompt: "Nextcloud MariaDB password"
      private: yes
    - name: your_domain
      prompt: "Your domain"
      private: no
    - name: nextcloud_port
      prompt: "Nextcloud HTTPS port"
      default: 8443
      private: no
    - name: nextcloud_instance_name
      prompt: "Nextcloud instance name (URL will be https://[thisvalue].[your_domain])"
      default: "nextcloud"
      private: no
  roles: 
    - {role: lemp_stack}
    - {role: letsencrypt_dns_challenge}
    - {role: nextcloud_installation}
